# Rad s matricama - numpy

numpy je Python-ov modul za rad s matricama.

In [1]:
import numpy as np

** Stvaranje vektora i matrice **

In [2]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [3]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

** Dimenzija vektora i matrice **

In [4]:
y.shape

(3,)

In [5]:
x.shape

(2, 3)

** Postavljanje vrijednosti **

In [6]:
y[2] = 100
y

array([  1,   2, 100])

In [7]:
x[1, 0] = 100
x

array([[  1,   2,   3],
       [100,   5,   6]])

** Stvaranje nul matrice **

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 3. Minimalna udaljenost

## 3.1. Matrica udaljenosti

Napravi funkciju ** edit_dist_mx() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * matrica udaljenosti između s1 i s2
    
Na primjer, matrica udaljenosti za s1 = "nos" i s2 = "noj" je

    [[0, 1, 2, 3],  
     [1, 0, 1, 2],  
     [2, 1, 0, 1],  
     [3, 2, 1, 2]]

Odnosno 

         #	n	o	j  
    #	0	1	2	3  
    n	1	0	1	2  
    o	2	1	0	1  
    s	3	2	1	2  

In [10]:
from opj_v03_test import *

def edit_dist_mx(s1, s2):
    n, m = len(s1), len(s2)
    mx = np.zeros((n + 1, m + 1), dtype=int)

    for i in range(n + 1):
        mx[i, 0] = i
    for j in range(m + 1):
        mx[0, j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            mx[i, j] = min(
                mx[i - 1, j] + 1,
                mx[i, j - 1] + 1,
                mx[i - 1, j - 1] + (2 if s1[i - 1] != s2[j - 1] else 0)
            )

    return mx


def edit_dist(s1, s2):
    return edit_dist_mx(s1, s2)[-1, -1]
    

testname(edit_dist)
test_dist(edit_dist_mx, edit_dist, ('nos','noj'), ([[0, 1, 2, 3], 
                                                    [1, 0, 1, 2], 
                                                    [2, 1, 0, 1], 
                                                    [3, 2, 1, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('osa','bosa'), ([[0, 1, 2, 3, 4], 
                                                     [1, 2, 1, 2, 3], 
                                                     [2, 3, 2, 1, 2], 
                                                     [3, 4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('bosa','osa'), ([[0, 1, 2, 3], 
                                                     [1, 2, 3, 4], 
                                                     [2, 1, 2, 3], 
                                                     [3, 2, 1, 2], 
                                                     [4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('paliti','piti'), ([[0, 1, 2, 3, 4], 
                                                        [1, 0, 1, 2, 3], 
                                                        [2, 1, 2, 3, 4], 
                                                        [3, 2, 3, 4, 5], 
                                                        [4, 3, 2, 3, 4], 
                                                        [5, 4, 3, 2, 3], 
                                                        [6, 5, 4, 3, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('paliti','pisati'), ([[0, 1, 2, 3, 4, 5, 6], 
                                                          [1, 0, 1, 2, 3, 4, 5], 
                                                          [2, 1, 2, 3, 2, 3, 4], 
                                                          [3, 2, 3, 4, 3, 4, 5], 
                                                          [4, 3, 2, 3, 4, 5, 4], 
                                                          [5, 4, 3, 4, 5, 4, 5], 
                                                          [6, 5, 4, 5, 6, 5, 4]], 4))


EDIT_DIST
------------------------------------------------------------
OK	udaljenost između 'nos' i 'noj' je 2
 	#	n	o	j
#	0	1	2	3
n	1	0	1	2
o	2	1	0	1
s	3	2	1	2


OK	udaljenost između 'osa' i 'bosa' je 1
 	#	b	o	s	a
#	0	1	2	3	4
o	1	2	1	2	3
s	2	3	2	1	2
a	3	4	3	2	1


OK	udaljenost između 'bosa' i 'osa' je 1
 	#	o	s	a
#	0	1	2	3
b	1	2	3	4
o	2	1	2	3
s	3	2	1	2
a	4	3	2	1


OK	udaljenost između 'paliti' i 'piti' je 2
 	#	p	i	t	i
#	0	1	2	3	4
p	1	0	1	2	3
a	2	1	2	3	4
l	3	2	3	4	5
i	4	3	2	3	4
t	5	4	3	2	3
i	6	5	4	3	2


OK	udaljenost između 'paliti' i 'pisati' je 4
 	#	p	i	s	a	t	i
#	0	1	2	3	4	5	6
p	1	0	1	2	3	4	5
a	2	1	2	3	2	3	4
l	3	2	3	4	3	4	5
i	4	3	2	3	4	5	4
t	5	4	3	4	5	4	5
i	6	5	4	5	6	5	4




Napravi funkciju ** align() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * Uređeni par ** (as1, as2) ** gdje je as1 poravnanje od s1, a as2 poravnanje od s2 (prilikom poravnanja koristiti "-")
    
NAPOMENA: poravnanje (izbor operacije) napraviti po sljedećim prioritetima:
1. zamjena
2. brisanje
3. ubacivanje
    
Primjer, poravnanje od 'paliti' i 'pisati':

    p--aliti  
    pisa--ti


In [11]:
def align(S, T):
    D = edit_dist_mx(S, T)

    m, n = len(S), len(T)
    i, j = m, n
    seq = ""
    as1, as2 = "", ""
    while (i, j) != (0, 0):
        if i > 0 and j > 0 and D[i, j] == D[i - 1, j - 1] and S[i - 1] == T[j - 1]:
            seq += "o"
            as1 += S[i - 1]
            as2 += T[j - 1]
            i -= 1
            j -= 1    
        elif i > 0 and j > 0 and D[i, j] == D[i - 1, j - 1] + 2 and S[i - 1] != T[j - 1]:
            seq += "z"
            as1 += S[i - 1]
            as2 += T[j - 1]
            i -= 1
            j -= 1
        elif j == 0 or D[i, j] == D[i - 1, j] + 1:
            seq += "b"
            as1 += S[i - 1]
            as2 += "-"            
            i -= 1
        elif i == 0 or D[i, j] == D[i, j - 1] + 1:
            seq += "u"
            as1 += "-"
            as2 += T[j - 1]
            j -= 1
    return "".join(reversed(as1)), "".join(reversed(as2))

testname(align)
test_alignment(align, ('nos','noj'), {('no-s', 'noj-'), ('nos-', 'no-j'), ('nos', 'noj')})
test_alignment(align, ('osa','bosa'), ('-osa', 'bosa'))
test_alignment(align, ('bosa','osa'), ('bosa', '-osa'))
test_alignment(align, ('paliti','piti'), ('paliti', 'p--iti'))
test_alignment(align, ('paliti','pisati'), {('pali--ti', 'p--isati'), ('p--aliti', 'pisa--ti')})
test_alignment(align, ('tradicija', 'dedukcija'), {('tra-di--cija', '-d-ed-ukcija'), ('-trad--icija', 'de--duk-cija'), ('trad--icija', 'de-duk-cija'), ('tra-d--icija', '-d-eduk-cija'), ('t--rad--icija', '-de--duk-cija'), ('tr-adi-cija', '-de-dukcija'), ('-tradi-cija', 'de--dukcija'), ('tr-a-d-icija', '--d-edukcija'), ('tra-d-icija', '-d-edukcija'), ('trad-icija', '-dedukcija'), ('--trad-icija', 'de---dukcija'), ('tradi-cija', 'de-dukcija'), ('trad--i-cija', '---dedukcija'), ('tr-ad-i-cija', '-de-du-kcija'), ('tra--di-cija', '---dedukcija'), ('t--radi-cija', '-de--dukcija'), ('trad--icija', '-deduk-cija'), ('t-ra-di--cija', '-d--ed-ukcija'), ('-tradi-cija', 'd--edukcija'), ('tra-d--icija', 'd--eduk-cija'), ('t-radi--cija', '-d-ed-ukcija'), ('t-rad--icija', '-d-eduk-cija'), ('tr-ad-i-cija', 'd-e-du-kcija'), ('tra--d-icija', '---dedukcija'), ('tradi--cija', 'd-ed-ukcija'), ('t-ra-d-icija', '-d--edukcija'), ('tra-d-icija', 'd--edukcija'), ('t-rad--icija', 'de--duk-cija'), ('t--rad-icija', '-de--dukcija'), ('t-ra-di-cija', '-d--edukcija'), ('tr-ad--icija', 'd-e-duk-cija'), ('-tradi-cija', 'd-e-dukcija'), ('-trad--icija', 'd--eduk-cija'), ('tr-adi-cija', '--dedukcija'), ('tr-adi--cija', '--ded-ukcija'), ('tr-a-d--icija', '--d-eduk-cija'), ('-tr-ad-icija', 'd--e-dukcija'), ('-tr-ad-i-cija', 'd--e-du-kcija'), ('tradi--cija', 'de-d-ukcija'), ('tra-d-icija', '--dedukcija'), ('tr--adi-cija', '--de-dukcija'), ('tr-ad-i-cija', '--dedu-kcija'), ('tra--d--icija', '---deduk-cija'), ('-tra-d--icija', 'd---eduk-cija'), ('tra-di-cija', '-d-edukcija'), ('-tradi--cija', 'd--ed-ukcija'), ('t-r-ad-i-cija', '-d-e-du-kcija'), ('tra-d-i-cija', '-d-edu-kcija'), ('-trad-i-cija', 'd-e-du-kcija'), ('tradi---cija', '---dedukcija'), ('tr-adi-cija', 'd-e-dukcija'), ('-trad-icija', 'de--dukcija'), ('-t-rad-icija', 'd-e--dukcija'), ('tr-adi--cija', '-de-d-ukcija'), ('-t-radi-cija', 'd-e--dukcija'), ('--trad--icija', 'de---duk-cija'), ('tr-a-d-i-cija', '--d-edu-kcija'), ('tr-ad-icija', '-de-dukcija'), ('tr--ad--icija', '--de-duk-cija'), ('-trad--icija', 'd-e-duk-cija'), ('-tr-ad--icija', 'd--e-duk-cija'), ('tr-ad--icija', '-de-duk-cija'), ('tradi-cija', '-dedukcija'), ('t-r-adi-cija', '-d-e-dukcija'), ('t-radi-cija', '-d-edukcija'), ('-tr-adi-cija', 'd--e-dukcija'), ('-trad-icija', 'd--edukcija'), ('--trad-i-cija', 'de---du-kcija'), ('t-rad-icija', '-de-dukcija'), ('t-radi-cija', 'de--dukcija'), ('t-rad-icija', '-d-edukcija'), ('tra-di--cija', 'd--ed-ukcija'), ('trad-icija', 'd-edukcija'), ('tra-di-cija', 'd--edukcija'), ('trad-i-cija', '-dedu-kcija'), ('tra-d-i-cija', '--dedu-kcija'), ('tr--ad-i-cija', '--de-du-kcija'), ('--tradi--cija', 'de---d-ukcija'), ('t-rad-i-cija', 'de--du-kcija'), ('-t-rad--icija', 'd-e--duk-cija'), ('-tra-di--cija', 'd---ed-ukcija'), ('t-ra-d--icija', '-d--eduk-cija'), ('-tradi--cija', 'de--d-ukcija'), ('t-rad--icija', '-de-duk-cija'), ('t-rad-icija', 'de--dukcija'), ('trad-i-cija', 'de-du-kcija'), ('tra-d--icija', '--deduk-cija'), ('tradi----cija', '---d-edukcija'), ('tra-di--cija', '--ded-ukcija'), ('tr-ad--icija', '--deduk-cija'), ('t-r-ad-icija', '-d-e-dukcija'), ('-trad-i-cija', 'd--edu-kcija'), ('tra-di-cija', '--dedukcija'), ('trad--i--cija', '---ded-ukcija'), ('t-ra-d-i-cija', '-d--edu-kcija'), ('-tr-adi--cija', 'd--e-d-ukcija'), ('t-radi--cija', 'de--d-ukcija'), ('tr-ad-icija', '--dedukcija'), ('trad-i-cija', 'd-edu-kcija'), ('-tra-d-i-cija', 'd---edu-kcija'), ('trad---icija', '---dedukcija'), ('-t-radi--cija', 'd-e--d-ukcija'), ('tr-adi--cija', 'd-e-d-ukcija'), ('t-radi-cija', '-de-dukcija'), ('tr-ad-icija', 'd-e-dukcija'), ('trad-icija', 'de-dukcija'), ('trad--icija', 'd-eduk-cija'), ('--tradi-cija', 'de---dukcija'), ('tr--ad-icija', '--de-dukcija'), ('tradi--cija', '-ded-ukcija'), ('t-rad-i-cija', '-de-du-kcija'), ('tr--adi--cija', '--de-d-ukcija'), ('trad----icija', '---deduk-cija'), ('-tra-di-cija', 'd---edukcija'), ('t-rad-i-cija', '-d-edu-kcija'), ('tr-a-di-cija', '--d-edukcija'), ('-tradi--cija', 'd-e-d-ukcija'), ('-trad-i-cija', 'de--du-kcija'), ('t--radi--cija', '-de--d-ukcija'), ('t-radi--cija', '-de-d-ukcija'), ('t-r-adi--cija', '-d-e-d-ukcija'), ('tra--d-i-cija', '---dedu-kcija'), ('-tra-d-icija', 'd---edukcija'), ('-trad-icija', 'd-e-dukcija'), ('tr-a-di--cija', '--d-ed-ukcija'), ('tradi-cija', 'd-edukcija'), ('t--rad-i-cija', '-de--du-kcija'), ('t-r-ad--icija', '-d-e-duk-cija'), ('trad-i--cija', '---dedukcija'), ('tra--di--cija', '---ded-ukcija'), ('tra-d-i-cija', 'd--edu-kcija'), ('-t-rad-i-cija', 'd-e--du-kcija'), ('trad---i-cija', '---dedu-kcija'), ('trad-i---cija', '---de-dukcija')})


ALIGN
------------------------------------------------------------
OK	poravnanje od 'nos' i 'noj':
nos
noj

OK	poravnanje od 'osa' i 'bosa':
-osa
bosa

OK	poravnanje od 'bosa' i 'osa':
bosa
-osa

OK	poravnanje od 'paliti' i 'piti':
paliti
p--iti

OK	poravnanje od 'paliti' i 'pisati':
p--aliti
pisa--ti

OK	poravnanje od 'tradicija' i 'dedukcija':
trad-icija
-dedukcija

